### ISSUE TITLE
Cannot run discover

### ISSUE THREAD

**Issue by rkatti** [totem/discover#8]
After building it from this docker file 

FROM totem/ubuntu:raring
RUN apt-get update --fix-missing && apt-get upgrade -y
RUN apt-get install -y wget curl build-essential patch git-core openssl libssl-dev unzip
RUN curl http://nodejs.org/dist/v0.10.20/node-v0.10.20-linux-x64.tar.gz | tar xzvf - --strip-components=1 -C "/usr"
RUN apt-get clean && rm -rf /var/cache/apt/archives/\* /var/lib/apt/lists/*
RUN npm install -g node-static
ENV DISCOVER "static-web-server:8080"
ENTRYPOINT ['static']

I get the following error

docker run -p 8080 static-web-server
/bin/sh: 1: [static]: not found

**Comment by mmoulton** [comment]
Investigating, will let you know what I find.

**Comment by mmoulton** [comment]
The README has been updated to reflect the latest working Dockerfile.
